config/routes.rb
CampusPeer::Application.routes.draw do
  get "ajax/campus"

  get "most_wanted_book/index"

  resources :book_transactions, :except => [:edit, :update, :delete] do
    collection do
      get 'search', :as => :search
    end
  end
  
  get "welcome/index"

  devise_for :users
  devise_scope :user do
    get "signin" => "devise/sessions#new"
    get "signout" => "devise/sessions#destroy"
  end

  get "homepage/index"
  
  resources :sell_book_items

   root :to => 'welcome#index'

end

app/controllers/book_transactions_controller.rb
class BookTransactionsController < ApplicationController

  helper_method :sort_column, :sort_direction

  # GET /book_transactions
  # GET /book_transactions.json
  def index
    @books_to_buy = BookTransaction.search(params[:search], current_user.campus_id, true)
    @books = @books_to_buy.collect { |book| book.book }

    if @books_to_buy
      respond_to do |format|
        format.html # index.html.erb
        format.js
        format.json { render json: @books_to_buy }
      end
    else
      redirect_to book_transactions_path
    end
  end

  def search
    #@books_to_buy = BookTransaction.search(params[:search], current_user.campus_id, false).page(params[:page]).per(1)
    @books_to_buy = Kaminari.paginate_array(BookTransaction.search(params[:search], current_user.campus_id, false)).page(params[:page]).per(1)

    # Kaminari.paginate_array(my_array_object).page(params[:page]).per(10)

    if @books_to_buy
      respond_to do |format|
        format.html # search.html.erb
        format.js
        format.json { render json: @books_to_buy }
      end
    else
      redirect_to search_book_transactions_path
    end
  end

  # GET /book_transactions/1
  # GET /book_transactions/1.json
  def show
    begin
      @book_transaction = BookTransaction.find(params[:id])
      @seller = User.find(@book_transaction.seller_user_id)

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @book_transaction }
      end
    rescue Exception => e
      redirect_to book_transactions_path
    end
  end

  # GET /book_transactions/new
  # GET /book_transactions/new.json
  def new
    @sell_book_items = SellBookItem.joins(:book).where(["sell_book_items.campus_id = ? AND books.isbn13 LIKE ?", current_user.campus_id, params[:buy_book]]).includes(:user, :book).order(sort_column + " " + sort_direction).page(params[:page]).per(2)
    
    unless @sell_book_items.empty?
      unless session["buy_book_new_#{@sell_book_items.first.book.id}"]  # Most wanted should only be updated on unique requests.
        MostWantedBook.update_most_wanted(@sell_book_items.first.book.id, current_user.campus_id)
        session["buy_book_new_#{@sell_book_items.first.book.id}"] = true
      end
      
      respond_to do |format|
        format.html # new.html.erb
        format.js
        format.json { render json: @sell_book_items }
      end
    else
      redirect_to book_transactions_path
    end
  end

  # POST /book_transactions
  # POST /book_transactions.json
  def create 
    sell_book_item = SellBookItem.find(params[:buy_book])
    @book_transaction = BookTransaction.new(:sell_book_item_id => sell_book_item.id,
                                            :book_id => sell_book_item.book_id,
                                            :seller_user_id => sell_book_item.user_id,
                                            :buyer_user_id => current_user.id,
                                            :campus_id => sell_book_item.campus_id,
                                            :price => sell_book_item.price,
                                            :condition => sell_book_item.condition,
                                            :condition_description => sell_book_item.condition_description)
    
    @book_transaction.peertag = generate_peertag

    respond_to do |format|
      if @book_transaction.save
        SellBookItem.delete(@book_transaction.sell_book_item_id)  # Delete the book from sell_book_items table.        
        format.html { redirect_to @book_transaction, notice: 'Book transaction was successfully created.' }
        format.json { render json: @book_transaction, status: :created, location: @book_transaction }

        # Send email to both buyer and seller.

      else
        format.html { render action: "new" }
        format.json { render json: @book_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def sort_column
      %w[price condition].include?(params[:sort]) ? params[:sort] : "price"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

=begin
  # GET /book_transactions/1/edit
  def edit
    @book_transaction = BookTransaction.find(params[:id])
  end
=end

=begin
  # PUT /book_transactions/1
  # PUT /book_transactions/1.json
  def update
    @book_transaction = BookTransaction.find(params[:id])

    respond_to do |format|
      if @book_transaction.update_attributes(params[:book_transaction])
        format.html { redirect_to @book_transaction, notice: 'Book transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book_transaction.errors, status: :unprocessable_entity }
      end
    end
  end
=end

=begin
  # DELETE /book_transactions/1
  # DELETE /book_transactions/1.json
  def destroy
    @book_transaction = BookTransaction.find(params[:id])
    @book_transaction.destroy

    respond_to do |format|
      format.html { redirect_to book_transactions_url }
      format.json { head :no_content }
    end
  end
=end

end

app/helpers/book_transactions_helper.rb
module BookTransactionsHelper
end

app/views/book_transactions/_buyitems.html.erb
<table class="table1">
  <tr>
    <th>User</th>
    <th id="price-cell"><%= sortable("price", nil, {:buy_book => params[:buy_book]}) %></th>
    <th id="condition-cell"><%= sortable("condition", nil, {:buy_book => params[:buy_book]}) %></th>
    <th>Condition Description</th>
    <th></th>
  </tr>

<% @sell_book_items.each_with_index do |sell_book_item, index| %>
  <tr <%= index % 2 == 0 ? "class = r0" : "class = r1" %>>
    <td id="user-image-cell">
      <div><%= image_tag("/assets/shared/UserNoImage.png", :class => "profile-pic") %></div>
      <div><%= sell_book_item.user.firstname %></div>
    </td>
    <td><%= number_to_currency(sell_book_item.price) %></td>
    <td ><%= sell_book_item.condition %></td>
    <td id="condition-description-cell"><%= sell_book_item.condition_description.blank? ? "No Description" : sell_book_item.condition_description %></td>
    <td class = "buy-cell" ><%= link_to image_tag("/assets/BookTransactions/TransparentBuyBookBtn3.png"), book_transactions_path({ :buy_book => sell_book_item.id }), :method => :post, :class => "bbb" %></td>
  </tr>
<% end %>
</table>

<br />
<%= paginate @sell_book_items %>

app/views/book_transactions/_search.html.erb
<% unless @books_to_buy.empty? %>
  <table class="table1">
    <tr>
      <th>Cover</th>
      <th>Title</th>
      <th>Author</th>
      <th>ISBN 10/13</th>
      <th>Publisher</th>
    </tr>

  <% @books_to_buy.each_with_index do |sell_book_item, index| %>
    <tr <%= index % 2 == 0 ? "class = r0" : "class = r1" %>>
      <td id ="bk-cover-cell"><%= link_to (image_tag(Book.cover(sell_book_item.book.isbn13), :alt => "#{sell_book_item.book.isbn13} Cover", :class => "bk-cover")), new_book_transaction_path({:buy_book => sell_book_item.book.isbn13})%></td>
      <td class="truncate"><%= link_to sell_book_item.book.title, new_book_transaction_path({:buy_book => sell_book_item.book.isbn13})%></td>
      <td ><%= sell_book_item.book.author %></td>
      <td id="isbn-cell"><%= sell_book_item.book.isbn10 %> <br/> <%= sell_book_item.book.isbn13%></td>
      <td id="publisher-cell"><%= sell_book_item.book.publisher %></td>
    </tr>
  <% end %>
  </table>

  <br />
  <%= paginate @books_to_buy %>
<% end %>

app/views/book_transactions/index.html.erb
<% content_for :head do %>
  <title>CampusPeer | Buy</title>
  <%= stylesheet_link_tag "book_transactions", :media => "all" %>
  <%= stylesheet_link_tag "search", :media => "all" %>
  <%= stylesheet_link_tag "placeholder", :media => "all" %>
  <%= javascript_include_tag "books" %>
  <%= javascript_include_tag "effects" %>
<% end %>

<div id="page-title">
  <%= image_tag("/assets/BookTransactions/bbtabcBar.png")%>
</div>
<div id="stw">Spread The Word!</div>

<div>
<div id="searchform">
  <%= form_tag book_transactions_path, :method => 'get', :id => "books-search" do %>
  <div>
    <label class="input3">
    <span>Enter ISBN or Title</span>
    <%= text_field_tag :search, params[:search], :id => "searchbox", :class => "autofocus"%>
    </label>
  </div>
   <div><%= submit_tag "", :name => nil, :type => :image, :src => "/assets/Shared/TransparentSearchBtn.png", :id => "search-btn" %></div>
<% end %>
</div>

<div id="tip">Tip: To ensure optimal results, <br/> &nbsp
&nbsp &nbsp search by ISBN.</div>
<br /><br/>

<div id="books-area">
 <%= render 'shared/books', { :books => @books, :path => "buy" } %>
</div>
<br />

<div id="scattered-books"></div>

<div id="loading"></div>

app/views/book_transactions/index.js.erb
toggleLoading()

$('#books-area').html('<%= escape_javascript(render 'shared/books', { :books => @books, :path => "buy" }) %>');

toggleNoResults();

flyInBooks();
initBooksQtips();

app/views/book_transactions/new.html.erb
<% content_for :head do %>
  <title>CampusPeer | Buy <%= @sell_book_items.first.book.title %></title>
  <%= stylesheet_link_tag "book_transactions_new", :media => "all" %>
  <%= stylesheet_link_tag "book", :media => "all" %>
  <%= stylesheet_link_tag "table", :media => "all" %>
  <%= javascript_include_tag "book_transactions_new" %>
<% end %>

<div id="bk-div">
  <div id="border">
    <div id="box-title">Book Summary</div>
  </div>

  <div id="bk-cover-div">
    <%= image_tag(Book.cover(@sell_book_items.first.book.isbn13), :alt => "#{@sell_book_items.first.book.isbn13} Cover", :id => "bk-cover") %>
  </div>

  <div id="bk-info-div">
    <table cellspacing ="9" class = "tble">
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">TITLE:</span></td>
        <td class="truncate"><%= @sell_book_items.first.book.title %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">AUTHORS:</span></td>
        <td class="truncate"><%= @sell_book_items.first.book.author %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">ISBN 10:</span></td>
        <td ><%= @sell_book_items.first.book.isbn10 %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">ISBN 13:</span></td>
        <td><%= @sell_book_items.first.book.isbn13 %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">PUBLISHER:</span></td>
        <td><%= @sell_book_items.first.book.publisher %></td>
      </tr>
    </table>
  </div>
</div>

<br />

<div id="buyitems">
  <%= render 'buyitems' %>
</div>

app/views/book_transactions/new.js.erb
$("#buyitems").html("<%= escape_javascript(render("buyitems")) %>")

app/views/book_transactions/search.html.erb
<% content_for :head do %>
  <title>CampusPeer | More Results</title>
  <%= stylesheet_link_tag "book_transactions_search", :media => "all" %>
  <%= stylesheet_link_tag "table", :media => "all" %>
  <%= stylesheet_link_tag "search", :media => "all" %>
  <%= stylesheet_link_tag    "placeholder", :media => "all" %>
  <%= javascript_include_tag "book_transactions_search" %>
<% end %>

<div id="page-title">More Results</div>

<br />

<div id="searchform2">
  <%= form_tag search_book_transactions_path, :method => 'get', :id => "search-form2" do %>
  <label class ="input2">
    <span> Enter ISBN or Title </span>
    <%= text_field_tag :search, params[:search], :id => "searchbox2", :class => "autofocus"%>
  </label>
    <%= submit_tag "", :name => nil, :type => :image, :src => "/assets/Shared/TransparentMoreResultsSearchBtn.png", :id => "search-btn2" %>
  <% end %>
</div>

<div id="search-items">
  <%= render 'search' %>
</div>

app/views/book_transactions/search.js.erb
$("#search-items").html("<%= escape_javascript(render("search")) %>")

app/views/book_transactions/show.html.erb
<% content_for :head do %>
  <title>CampusPeer | Receipt</title>
  <%= stylesheet_link_tag "book_transactions_show", :media => "all" %>
  <%= stylesheet_link_tag "book", :media => "all" %>
<% end %>

<div id="bk-div">
  <div id="border">
    <div id="box-title">Receipt</div>
  </div>

  <div id="bk-cover-div">
    <%= image_tag(Book.cover(@book_transaction.book.isbn13), :alt => "#{@book_transaction.book.isbn13} Cover", :id => "bk-cover") %>
  </div>

  <div id="bk-info-div">
    <table cellspacing = "9" class ="tble">
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">Title:</span></td>
        <td class="truncate"><%= @book_transaction.book.title %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">Author:</span></td>
        <td><%= @book_transaction.book.author %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">ISBN 10:</span></td>
        <td><%= @book_transaction.book.isbn10 %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">ISBN 13:</span></td>
        <td><%= @book_transaction.book.isbn13 %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">Publisher:</span></td>
        <td><%= @book_transaction.book.publisher %></td>
      </tr>

      <tr><td class= "dash"></td><td class="dash"></td></tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">Seller:</span></td>
        <td><%= "#{@seller.firstname} #{@seller.lastname}" %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">Price:</span></td>
        <td><%= number_to_currency(@book_transaction.price) %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">Condition:</span></td>
        <td><%= @book_transaction.condition %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">Condition Description:</span></td>
        <td class="truncate" id="bk-value-width-show" ><%= @book_transaction.condition_description.blank? ? "No Description" : @book_transaction.condition_description %></td>
      </tr>
      <tr>
        <td class="bk-heading-width"><span class="bk-heading">PeerTag:</span></td>
        <td><%= @book_transaction.peertag %></td>
      </tr>

    </table>
  </div>
</div>