config/routes.rb
CampusPeer::Application.routes.draw do
  get "ajax/campus"

  get "most_wanted_book/index"

  resources :book_transactions, :except => [:edit, :update, :delete] do
    collection do
      get 'search', :as => :search
    end
  end
  
  get "welcome/index"

  devise_for :users
  devise_scope :user do
    get "signin" => "devise/sessions#new"
    get "signout" => "devise/sessions#destroy"
  end

  get "homepage/index"
  
  resources :sell_book_items

   root :to => 'welcome#index'

end

app/models/most_wanted_book.rb
class MostWantedBook < ActiveRecord::Base
  belongs_to :campus
  belongs_to :book

  def self.update_most_wanted(book, campus)
  	wantedBook = MostWantedBook.where(["book_id = ? AND campus_id = ?", book, campus]).first

  	if wantedBook
  	  wantedBook.want += 1
  	  wantedBook.save
  	else
  	  MostWantedBook.create(:book_id => book, :campus_id => campus, :want => 1)
  	end
  end

  # Get a specific ammount of most wanted books within the last 5 months for a specific campus.
  def self.get_most_wanted(ammount, campus)
  	books = Book.joins(:most_wanted_books).where(["most_wanted_books.updated_at > ? AND most_wanted_books.campus_id = ?", DateTime.now.months_ago(5), campus]).order("most_wanted_books.want DESC").limit(ammount)
  	if !books.empty?
  		if books.size < ammount
        book_ids = books.collect { |book| book.id}
	  	  books += Book.where(["id NOT IN (?)", book_ids]).limit(ammount - books.size)
	  	end
  	else
  	  books = Book.limit(ammount)
  	end
    books
  end

  # Search through the most wanted books within the last 5 months for a specific campus.
  def self.search_most_wanted(search, campus)
    if (search && !search.empty?)
      if /^\d+X{0,1}$/u === search
        books = Book.joins(:most_wanted_books).where(["most_wanted_books.updated_at > ? AND (books.isbn10 LIKE ? OR books.isbn13 LIKE ?) AND most_wanted_books.campus_id = ?", DateTime.now.months_ago(5), "%#{search}%", "%#{search}%", campus]).order("most_wanted_books.want DESC")
        if ((search.length == 10 or search.length == 13) and books[0].nil?)
          Book.advancedSearch(search)
        end
      else
        books = Book.joins(:most_wanted_books).where(["most_wanted_books.updated_at > ? AND books.title LIKE ? AND most_wanted_books.campus_id = ?", DateTime.now.months_ago(5), "%#{search}%", campus]).order("most_wanted_books.want DESC")
      end
    else
      books = Book.joins(:most_wanted_books).where(["most_wanted_books.updated_at > ? AND most_wanted_books.campus_id = ?", DateTime.now.months_ago(5), campus]).order("most_wanted_books.want DESC")
    end
    books
  end

end

app/controllers/most_wanted_book_controller.rb
class MostWantedBookController < ApplicationController
  def index
  	@books = MostWantedBook.search_most_wanted(params[:search], current_user.campus_id).page(params[:page]).per(2)

    if @books
      respond_to do |format|
        format.html # index.html.erb
        format.js
        format.json { render json: @books }
      end
    else
      redirect_to sell_book_items_path
    end
  end
end

app/helpers/most_wanted_book_helper.rb
module MostWantedBookHelper
end

app/views/most_wanted_book/_search.html.erb
<% unless @books.empty? %>
  <table class="table1">
    <tr>
      <th>Cover</th>
      <th>Title</th>
      <th>Author</th>
      <th>ISBN 10/13</th>
      <th>Publisher</th>
    </tr>

  <% @books.each_with_index do |book, index| %>
    <tr <%= index % 2 == 0 ? "class = r0" : "class = r1" %>>
      <td id="bk-cover-cell"><%= link_to (image_tag(Book.cover(book.isbn13), :alt => "#{book.isbn13} Cover", :class => "bk-cover")), new_sell_book_item_path({:book => book}) %></td>
      <td class="truncate"><%= link_to book.title, new_sell_book_item_path({:book => book}) %></td>
      <td><%= book.author %></td>
      <td id="isbn-cell"><%= book.isbn10 %> <br/> <%= book.isbn13 %></td>
      <td id="publisher-cell"><%= book.publisher%></td>
    </tr>
  <% end %>
  </table>

  <br />
  <%= paginate @books %>
<% end %>

app/views/most_wanted_book/index.html.erb
<% content_for :head do %>
  <title>CampusPeer | Most Wanted Books</title>
  <%= stylesheet_link_tag "most_wanted_book", :media => "all" %>
  <%= stylesheet_link_tag "table", :media => "all" %>
  <%= stylesheet_link_tag "search", :media => "all" %>
  <%= javascript_include_tag "most_wanted_book" %>
  <%= stylesheet_link_tag "placeholder", :media => "all" %>
<% end %>

<div id="page-title">Most Wanted Books</div>

<br />

<div id="searchform2">
  <%= form_tag search_book_transactions_path, :method => 'get', :id => "search-form2" do %>
  <label class ="input2">
    <span> Enter ISBN or Title </span>
    <%= text_field_tag :search, params[:search], :id => "searchbox2", :class => "autofocus"%>
  </label>
    <%= submit_tag "", :name => nil, :type => :image, :src => "/assets/Shared/TransparentMoreResultsSearchBtn.png", :id => "search-btn2" %>
  <% end %>
</div>

<div id="search-items">
  <%= render 'search' %>
</div>

app/views/most_wanted_book/index.js.erb
$("#search-items").html("<%= escape_javascript(render("search")) %>")